language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
before_script:
  - composer self-update
script:
  - composer install --no-interaction --prefer-source
  - vendor/bin/phing
after_script:
  - php vendor/bin/coveralls -v
